'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {createClient} from '../../lib/supabase/client'
import '../account-ui.css'

export default function Favorites(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true)
 useEffect(()=>{let active=true;const supabase=createClient();supabase.auth.getUser().then(async({data})=>{if(!data.user){window.location.href='/connexion';return}const {data:favorites}=await supabase.from('favorites').select('listing_id').eq('user_id',data.user.id);const ids=(favorites||[]).map(x=>x.listing_id);if(!ids.length){if(active)setLoading(false);return}const {data:rows}=await supabase.from('listings').select('id,title,price,transaction_mode,has_invoice,shipping,pickup,listing_photos(public_url,position)').in('id',ids);if(active){setItems(rows||[]);setLoading(false)}}).catch(()=>setLoading(false));return()=>{active=false}},[])
 async function remove(id){const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('favorites').delete().eq('user_id',user.id).eq('listing_id',id);setItems(current=>current.filter(x=>x.id!==id))}
 return <main><header className="simpleNav"><Link className="logo" href="/">Dealora<span>.</span></Link><Link href="/compte">Mon compte</Link></header><section className="account"><p className="eyebrow">VOTRE SÉLECTION</p><h1>Mes favoris</h1>{loading?<p>Chargement…</p>:items.length?<div className="grid compactGrid">{items.map(item=>{const photo=[...(item.listing_photos||[])].sort((a,b)=>a.position-b.position)[0];return <article className="card" key={item.id}><Link className="favoritePhoto" href={`/annonce/${item.id}`}>{photo?<img src={photo.public_url} alt={item.title}/>:<span>📦</span>}</Link><div className="cardbody"><small>{item.transaction_mode==='swap'?'Troc':item.transaction_mode==='auction'?'Enchère':'Achat'}</small><Link href={`/annonce/${item.id}`}><h3>{item.title}</h3></Link><strong>{item.transaction_mode==='swap'?'À échanger':`${Number(item.price||0).toLocaleString('fr-FR')} €`}</strong><p>🧾 Facture : {item.has_invoice?'Oui':'Non'} · {item.shipping?'Expédition disponible':'Remise en main propre'}</p><button className="removeFavorite" onClick={()=>remove(item.id)}>Retirer des favoris</button></div></article>})}</div>:<div className="emptyPanel"><p>Vous n’avez encore aucun favori.</p><Link className="primaryLink" href="/">Découvrir les annonces</Link></div>}</section></main>
}
