'use client'
import {useEffect,useRef,useState} from 'react'
import {supabase} from '../lib/supabase'
import {Search,MapPin,ShoppingCart,RefreshCw,Gavel,Leaf,Users,ShieldCheck,Heart,Home as HomeIcon,MessageCircle,User,Plus,Camera,ChevronRight,Clock,Star,Share2,X,SlidersHorizontal,ArrowLeft,Send} from 'lucide-react'
const categories=[['Maison & Déco','Des milliers d’annonces','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=500&q=85'],['High-Tech','Smartphones, PC, etc.','https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=500&q=85'],['Mode & Accessoires','Vêtements, sneakers...','https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=85'],['Véhicules','Voitures, motos...','https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=500&q=85']]
const seed=[['Canapé 3 places','250 €','Paris (75)','Il y a 2h','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=85'],['iPhone 13 – 128 Go','320 €','Lyon (69)','Il y a 4h','https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=600&q=85'],['Yamaha MT-07','5 800 €','Marseille (13)','Il y a 6h','https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=600&q=85'],['Table à manger','120 €','Bordeaux (33)','Il y a 8h','https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=600&q=85']]
export default function Home(){
 const [tab,setTab]=useState('Acheter'),[view,setView]=useState('home'),[selected,setSelected]=useState(null),[ads,setAds]=useState(seed),[query,setQuery]=useState(''),[favs,setFavs]=useState([]),[notice,setNotice]=useState(''),[user,setUser]=useState(null); const file=useRef(null)
 const toast=t=>{setNotice(t);setTimeout(()=>setNotice(''),1800)}
 const openAd=a=>{setSelected(a);setView('product');window.scrollTo(0,0)}
 const toggleFav=(name,e)=>{e?.stopPropagation();setFavs(v=>v.includes(name)?v.filter(x=>x!==name):[...v,name])}
 const share=async()=>{const data={title:selected?.[0]||'Dealora',text:'Découvrez cette annonce sur Dealora',url:window.location.href};if(navigator.share){try{await navigator.share(data)}catch{}}else{await navigator.clipboard?.writeText(window.location.href);toast('Lien copié')}}
 const nav=(v)=>{setView(v);setSelected(null);window.scrollTo(0,0)}
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user||null))},[])
 useEffect(()=>{let alive=true
  supabase.from('listings').select('id,title,price,created_at,listing_photos(public_url)').eq('status','active').order('created_at',{ascending:false}).limit(30).then(({data})=>{
   if(!alive||!data?.length)return
   const live=data.map(x=>[x.title,x.price==null?'À négocier':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(x.price),'France','Récent',x.listing_photos?.[0]?.public_url||'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=85'])
   setAds(live)
  })
  return()=>{alive=false}
 },[])
 const filtered=ads.filter(a=>a[0].toLowerCase().includes(query.toLowerCase())||a[2].toLowerCase().includes(query.toLowerCase()))
 const suggestions=query?ads.filter(a=>a[0].toLowerCase().includes(query.toLowerCase())).slice(0,4):[]
 const Card=({a})=><article onClick={()=>openAd(a)}><div className="pic"><img src={a[4]} alt={a[0]}/><button onClick={e=>toggleFav(a[0],e)} className={favs.includes(a[0])?'liked':''}><Heart/></button></div><div className="adText"><b>{a[0]}</b><strong>{a[1]}</strong><div><span><MapPin/>{a[2]}</span><small>{a[3]}</small></div></div></article>
 if(view==='product'&&selected) return <main className="dealora productPage"><header className="productHead"><button onClick={()=>nav('home')}>‹</button><b>dealora</b><div><button onClick={share}><Share2/></button><button onClick={e=>toggleFav(selected[0],e)} className={favs.includes(selected[0])?'liked':''}><Heart/></button></div></header><div className="productPhoto"><img src={selected[4]} alt={selected[0]}/><span>1 / 4</span></div><section className="productInfo"><div className="productPrice"><div><h1>{selected[0]}</h1><strong>{selected[1]}</strong></div><button onClick={e=>toggleFav(selected[0],e)}><Heart/></button></div><p className="meta"><MapPin/>{selected[2]} <span>•</span><Clock/>{selected[3]}</p><div className="dealModes"><span><ShoppingCart/> Achat direct</span><span><RefreshCw/> Troc possible</span><span><Gavel/> Offre acceptée</span></div><h2>Description</h2><p className="description">Article en très bon état, soigneusement entretenu. Disponible immédiatement. Contactez le vendeur pour plus d’informations ou pour faire une proposition.</p><div className="seller"><div className="avatar">M</div><div><b>Marie D.</b><span><Star/> 4,9 · 28 avis</span><small>Membre vérifié</small></div><ChevronRight/></div></section><div className="productActions"><button className="message" onClick={()=>nav('messages')}><MessageCircle/>Message</button><button className="buy" onClick={()=>toast('Achat sécurisé bientôt disponible')}><ShoppingCart/>Acheter</button></div>{notice&&<div className="toast">{notice}</div>}</main>
 if(view==='deposit') return <main className="dealora inner"><header className="innerHead"><button onClick={()=>nav('home')}><ArrowLeft/></button><b>Déposer une annonce</b><span/></header><form className="depositForm" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget),a=[d.get('title'),d.get('price')+' €',d.get('city'),'À l’instant','https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=85'];setAds(v=>[a,...v]);toast('Annonce publiée');setTimeout(()=>nav('home'),700)}}><div className="uploadBox"><Camera/><b>Ajouter des photos</b><small>Jusqu’à 8 photos</small></div><label>Titre<input name="title" required placeholder="Ex. iPhone 15 Pro 256 Go"/></label><label>Prix<input name="price" required type="number" placeholder="450"/></label><label>Localisation<input name="city" required placeholder="Paris (75)"/></label><label>Mode de transaction<select><option>Achat direct</option><option>Troc</option><option>Enchère</option></select></label><label>Description<textarea rows="5" placeholder="Décrivez l’état, les accessoires, la remise..."/></label><button className="publish">Publier mon annonce</button></form>{notice&&<div className="toast">{notice}</div>}</main>
 if(view==='messages') return <main className="dealora inner"><header className="innerHead"><button onClick={()=>nav('home')}><ArrowLeft/></button><b>Messages</b><span/></header><div className="conversation"><div className="chatSeller"><div className="avatar">M</div><div><b>Marie D.</b><small>En ligne récemment</small></div></div><div className="bubble other">Bonjour 👋 L’article est toujours disponible.</div><div className="bubble mine">Super, est-ce que le prix est négociable ?</div><div className="composer"><input placeholder="Écrire un message..."/><button><Send/></button></div></div></main>
 if(view==='account') return <main className="dealora inner"><header className="innerHead"><button onClick={()=>nav('home')}><ArrowLeft/></button><b>Mon compte</b><span/></header><section className="account"><div className="bigAvatar"><User/></div><h2>Votre espace Dealora</h2><p>Connectez-vous pour publier, sauvegarder vos favoris et retrouver vos conversations.</p><button className="publish">Se connecter / Créer un compte</button><div className="accountRow"><Heart/>Mes favoris <b>{favs.length}</b></div><div className="accountRow"><ShoppingCart/>Mes annonces <b>{Math.max(0,ads.length-seed.length)}</b></div></section></main>
 return <main className="dealora"><section className="hero"><div className="heroCopy"><div className="pill"><i/>Acheter autrement</div><h1>Tout peut avoir<br/><em>une seconde vie.</em></h1><p>Achetez, vendez, troquez ou enchérissez sur des milliers d'objets et de biens. Simplement, partout.</p></div><div className="globe">🌍</div><div className="searchbar"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Que recherchez-vous ?"/><input ref={file} type="file" accept="image/*" hidden/><button onClick={()=>file.current?.click()}><Camera/></button></div>{query&&suggestions.length>0&&<div className="suggestions">{suggestions.map(a=><button key={a[0]} onClick={()=>openAd(a)}><Search/><span>{a[0]}<small>{a[2]}</small></span><strong>{a[1]}</strong></button>)}</div>}<div className="tabs">{[[ShoppingCart,'Acheter'],[RefreshCw,'Troquer'],[Gavel,'Enchérir']].map(([I,n])=><button key={n} onClick={()=>setTab(n)} className={tab===n?'active':''}><I/>{n}</button>)}</div><div className="location"><span><MapPin/>France · Europe · International</span><button><MapPin/>Autour de moi</button></div><div className="benefits">{[[Leaf,'Économisez','Des prix plus justes'],[RefreshCw,'Donnez une seconde vie',''],[Users,'Une communauté de confiance',''],[ShieldCheck,'Des transactions plus sûres','']].map(([I,a,b])=><div key={a}><span><I/></span><b>{a}</b>{b&&<small>{b}</small>}</div>)}</div></section><section className="content"><div className="sectionTitle"><h2>Parcourir nos catégories</h2><button>Voir toutes →</button></div><div className="categories">{categories.map(([n,s,img])=><article key={n} onClick={()=>setQuery(n.split(' ')[0])}><img src={img} alt={n}/><b>{n}</b><small>{s}</small></article>)}</div><div className="sectionTitle recent"><h2>{query?'Résultats':'Près de chez vous'}</h2><button><SlidersHorizontal/> Filtres</button></div><div className="ads">{filtered.map(a=><Card key={a[0]} a={a}/>)}</div>{filtered.length===0&&<div className="empty">Aucune annonce trouvée. Essayez une autre recherche.</div>}</section><nav className="bottom">{[[HomeIcon,'Accueil','home'],[Search,'Rechercher','home'],[Plus,'Déposer','deposit'],[MessageCircle,'Messages','messages'],[User,'Mon compte','account']].map(([I,n,v],i)=><button key={n} onClick={()=>nav(v)} className={i===0?'on':i===2?'deposit':''}><span><I/></span>{n}</button>)}</nav></main>
}