'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../lib/supabase/client'
import {loadMessages,openConversation,sendMessage} from '../../lib/conversations'
import {watchMessages} from '../../lib/realtime'
import './messages.css'

export default function Messages(){
 const [user,setUser]=useState(null),[conversations,setConversations]=useState([]),[activeId,setActiveId]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[loading,setLoading]=useState(true),[status,setStatus]=useState('')
 useEffect(()=>{let active=true;const supabase=createClient();supabase.auth.getUser().then(async({data})=>{if(!data.user){window.location.href='/connexion';return}if(!active)return;setUser(data.user);let requestedId=null;const listingId=new URLSearchParams(window.location.search).get('listing');if(listingId){try{requestedId=await openConversation(listingId)}catch(error){setStatus(error.message==='OWN_LISTING'?'Vous ne pouvez pas démarrer une conversation sur votre propre annonce.':'Impossible d’ouvrir cette conversation.')}}const {data:rows,error}=await supabase.from('conversations').select('id,listing_id,buyer_id,seller_id,created_at,listings!conversations_listing_id_fkey(title),messages(id,body,sender_id,created_at)').or(`buyer_id.eq.${data.user.id},seller_id.eq.${data.user.id}`).order('created_at',{ascending:false});if(!active)return;if(error)setStatus('Impossible de charger vos conversations.');const list=rows||[];setConversations(list);setActiveId(requestedId||list[0]?.id||null);setLoading(false)}).catch(()=>setLoading(false));return()=>{active=false}},[])
 useEffect(()=>{if(!activeId)return;let active=true;loadMessages(activeId).then(rows=>{if(active)setMessages(rows)}).catch(()=>setStatus('Impossible de charger les messages.'));const stop=watchMessages(activeId,message=>setMessages(current=>current.some(x=>x.id===message.id)?current:[...current,message]));return()=>{active=false;stop()}},[activeId])
 const activeConversation=useMemo(()=>conversations.find(x=>x.id===activeId),[conversations,activeId])
 async function submit(event){event.preventDefault();const body=text.trim();if(!body||!activeId)return;setText('');setStatus('');try{await sendMessage(activeId,body);setMessages(await loadMessages(activeId))}catch{setText(body);setStatus('Votre message n’a pas pu être envoyé.')}}
 if(loading)return <main className="account"><p>Chargement de la messagerie…</p></main>
 return <main><header className="simpleNav"><Link className="logo" href="/">Dealora<span>.</span></Link><Link href="/compte">Mon compte</Link></header><section className="messagesPage"><div className="messagesTitle"><p className="eyebrow">MESSAGERIE SÉCURISÉE</p><h1>Vos conversations</h1></div>{status&&<p className="messageStatus">{status}</p>}<div className="messengerShell"><aside className="conversationList">{conversations.length?conversations.map(conversation=>{const ordered=[...(conversation.messages||[])].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const last=ordered.at(-1);return <button key={conversation.id} className={activeId===conversation.id?'active':''} onClick={()=>setActiveId(conversation.id)}><span className="conversationAvatar">{conversation.listings?.title?.[0]?.toUpperCase()||'D'}</span><span><b>{conversation.listings?.title||'Annonce Dealora'}</b><small>{last?.body||'Commencez la conversation'}</small></span></button>}):<div className="noConversation"><b>Aucune conversation</b><p>Contactez un vendeur depuis une annonce pour commencer.</p><Link href="/">Explorer Dealora</Link></div>}</aside><section className="chatPanel">{activeConversation?<><div className="chatHeader"><div><b>{activeConversation.listings?.title||'Annonce Dealora'}</b><small>Échanges protégés par Dealora</small></div><Link href={`/annonce/${activeConversation.listing_id}`}>Voir l’annonce</Link></div><div className="messageStream">{messages.length?messages.map(message=><div key={message.id} className={`messageBubble ${message.sender_id===user?.id?'mine':''}`}><p>{message.body}</p><small>{new Date(message.created_at).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></div>):<div className="startChat"><span>💬</span><b>Commencez la discussion</b><p>Posez vos questions sur l’objet, la facture ou la remise.</p></div>}</div><form className="messageComposer" onSubmit={submit}><input value={text} onChange={event=>setText(event.target.value)} maxLength="3000" placeholder="Écrivez votre message…" aria-label="Message"/><button type="submit" disabled={!text.trim()}>Envoyer</button></form></>:<div className="selectConversation"><span>💬</span><h2>Sélectionnez une conversation</h2><p>Vos échanges avec les acheteurs et vendeurs apparaîtront ici.</p></div>}</section></div><p className="safeNote">🛡️ Ne partagez jamais vos mots de passe ou codes de paiement. Gardez vos échanges dans Dealora.</p></section></main>
}
