'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {createClient} from '../../lib/supabase/client'
import '../account-ui.css'

export default function Account(){
 const [user,setUser]=useState(null),[profile,setProfile]=useState(null),[stats,setStats]=useState({listings:0,favorites:0,notifications:0,offers:0}),[loading,setLoading]=useState(true)
 useEffect(()=>{let active=true;const supabase=createClient();supabase.auth.getUser().then(async({data})=>{if(!data.user){window.location.href='/connexion';return}const id=data.user.id;const [profileResult,listingsResult,favoritesResult,notificationsResult,offersResult]=await Promise.all([supabase.from('profiles').select('display_name,rating,verified,country').eq('id',id).maybeSingle(),supabase.from('listings').select('*',{count:'exact',head:true}).eq('seller_id',id).eq('status','active'),supabase.from('favorites').select('*',{count:'exact',head:true}).eq('user_id',id),supabase.from('notifications').select('*',{count:'exact',head:true}).eq('user_id',id).is('read_at',null),supabase.from('offers').select('*',{count:'exact',head:true}).eq('buyer_id',id).eq('status','pending')]);if(!active)return;setUser(data.user);setProfile(profileResult.data);setStats({listings:listingsResult.count||0,favorites:favoritesResult.count||0,notifications:notificationsResult.count||0,offers:offersResult.count||0});setLoading(false)}).catch(()=>setLoading(false));return()=>{active=false}},[])
 async function logout(){await createClient().auth.signOut();window.location.href='/'}
 if(loading)return <main className="account"><p>Chargement de votre compte…</p></main>
 const name=profile?.display_name||user?.email?.split('@')[0]||'Membre Dealora';const initials=name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()
 return <main><header className="simpleNav"><Link className="logo" href="/">Dealora<span>.</span></Link><Link href="/vendre" className="pill">+ Déposer une annonce</Link></header><section className="account"><div className="profileCard"><div className="avatar">{initials}</div><div><p className="eyebrow">MON COMPTE</p><h1>{name} {profile?.verified&&'✓'}</h1><p>{profile?.rating?`⭐ ${profile.rating}/5 · `:''}{profile?.verified?'Profil vérifié · ':''}{profile?.country||'France'}</p></div></div><div className="dashboardGrid"><article><b>{stats.listings}</b><span>Annonces actives</span></article><article><b>{stats.favorites}</b><span>Favoris</span></article><article><b>{stats.notifications}</b><span>Notifications non lues</span></article><article><b>{stats.offers}</b><span>Offres en cours</span></article></div><div className="panel"><h2>Activité</h2><div className="accountLinks"><Link href="/vendre">📦 Vendre un objet</Link><Link href="/favoris">♡ Mes favoris</Link><Link href="/messages">💬 Messagerie</Link><Link href="/notifications">🔔 Mes notifications</Link></div><button className="logoutButton" onClick={logout}>Se déconnecter</button></div></section></main>
}
